avs:
  trigger: alexa
  silent: false
  Client_ID: ""
  Client_Secret: ""
  Device_Type_ID: "LEAPv3"
  Security_Profile_Description: ""
  Security_Profile_ID: ""
  refresh_token: ""

synthetizer:
  device: "alsa"
  handler: "vlc"
  volume: 100

microphone:
  device: "plughw:1"
  triggers:
    alexa: "alexa"
    stop: "stop"

platform:
  # Name of your platform, e.g. raspberrypi, orangepi, desktop
  device: [""]